django/chat/models.py, django/chat/views.py, django/initial_setup.sh
Because users in setup script were being created with `User.objects.aupdate_or_create` rather than `User.objects.create`, the setup code for creating a user personal library was not run.
I moved the code to create the personal library closer to where the error was occurring, so it doesn't rely on using the `User.objects.create` method.
There were also two other issues, unrelated but worth fixing at the same time:
1. Braces syntax in `initial_setup.sh`
2. Not loading `cost_types` in `initial_setup.sh`.
=> fix: setup issues

setup/k8s/celery.yaml
**purpose**: resolve OOMKilled restarts in k8s
already deployed in sandbox. since we have 2 nodes now, there is more than enough memory to go around
if OOM errors persist, we can continue tuning this.
=> ops: 4gb ram for celery worker pod

django/chat/views.py
Due to a change in models (reverse 1-1 relationship direction between Chat and DataSource/ChatOptions) there was a bug opening old chats. This fixes it.
=> fix: create chatoptions and chat datasource for old chats

django/chat/static/chat/js/scripts.js
Not sure if its the most elegant way of doing it, but it seems to work.
=> fix: dragging file into chat / uploading file clears the prompt

django/otto/settings.py, setup/terraform/modules/keyvault/main.tf
Solves an intermittent bug where Django connections cursor to the vectordb gives a password error.
Quoting the password in Django works for LlamaIndex, but not connections cursor, which does not unquote.
Simple solution is to remove the quoting and don't use special characters when generating the password.
=> fix: prevent special chars in vectordb password

django/chat/templates/chat/components/chat_options_accordion.html, django/chat/templates/chat/components/options_submenu.html, django/chat/urls.py, django/chat/views.py, django/librarian/static/librarian/scripts.js, django/librarian/templates/librarian/components/list_item.html, django/librarian/templates/librarian/forms/library.html, django/tests/chat/test_chat_views.py
From original ticket:
> When a library is added or deleted, the changes dont directly appear in the chat window, it gets fixed when i manually refresh the page. Can that process of refreshing be done automatically? it could be confusing for users when creating, editing, or deleting libraries in QnA
To test:
1:
* open librarian modal
* change libraries
* close the modal.
* sidebar should reflect the change
2:
* open modal
* create a library
* close the modal
* sidebar should reflect the change
3:
* open modal
* delete a library
* close the modal
* sidebar should reset to default library
4:
* select a particular data source in the sidebar
* open the modal
* don't do anything
* close the modal
* sidebar should be unchanged
=> fix: delete or create library bug (update sidebar)

django/.dockerignore, django/chat/templates/chat/chat_readonly.html, django/chat/templates/chat/components/message_actions.html, django/chat/utils.py, django/chat/views.py, django/locale/translation/translations.json, django/otto/forms.py, django/tests/chat/test_chat_procs.py, django/tests/chat/test_chat_readonly.py, django/tests/chat/test_chat_views.py
Users can copy the URL of their chat and share it with others. Any logged-in Otto user can view any other chat for which they have the link. Because the chats have UUIDs, this is not a security issue.
=> feat: view read-only chat from link

django/chat/models.py, django/chat/utils.py, django/chat/views.py
Reuse the (working) `_copy_options` method from chat/views.py in chat/models.py. (Moved to a public method in chat/utils.py)
=> fix: m2m fields in default preset; move copy_options to utils.py

django/librarian/views.py, django/tests/librarian/test_librarian.py
Fixes a bug where document processing status icons (in "documents" list for a particular data source in librarian modal) did not finish updating. i.e. "poll_url" was None in the context from the `poll_status` view even though there were ongoing tasks.
To test:
- start celery with a small number of concurrent tasks, i.e. 2
- upload some documents to a data source (more than 2)
- ensure that the status icons for all of them continues to update until all documents are complete, without any intervention
=> fix: librarian status updates

django/chat/forms.py
1. fix: an issue with chat Q&A retrieving duplicate libraries when the user shares a library with others and designates them as an admin.
=> fix: q&a managed libraries duplicates

django/librarian/views.py
Fixed bug where new created library didn't show up in the list of libraries after creation. The newly created library wasn't been returned as part of the libraries query due to cached permissions. @juleskuehn suggested invalidating cache right before querying the libraries again which solved the problem.
=> fix: create library new library not displayed in libraries list

django/librarian/utils/process_engine.py, django/text_extractor/tasks.py, django/text_extractor/utils.py
Different logics of image resizing depending on merged being on or off.
When merge is on - images resized to fit A4 dimensions following a new scale and DPI increased to 300 for clearer resolution.
When merge is off - single image resized as per azure requirements and eliminated pasting image over A4.
=> fix : changed logic of resizing

django/otto/models.py, django/otto/templates/components/feedback/dashboard/feedback_type_icon.html, django/otto/templates/components/feedback/dashboard/feedback_type_status.html, django/tests/otto/test_otto_models.py
In the course of working on something else, I noticed that there were 500 errors popping up in the Sandbox feedback manager. It turned out to be related to a feedback item with an obsolete Type category, which was breaking the custom feedback_type_display function in the Feedback model.
Fortunately, it turns out that Django provides a built-in display method in HTML templates, which does the same thing as the custom function but also allows for obsolete categories to be displayed.
=> fix: eliminate unnecessary display functions

django/chat/static/chat/js/scripts.js, django/chat/static/chat/style.css, django/chat/templates/chat/chat.html, django/chat/templates/chat/components/chat_history_sidebar.html
Makes sure chat is visible in sidebar onload
Ellipsis is shown by default for current chat as well.
=> feat: add smooth scrolling to current chat list item and enhance button visibility

django/chat/static/chat/js/chatOptions.js, django/chat/static/chat/js/scripts.js
Fixed a bug where QA advanced settings options weren't being reset even though the QA autocomplete form was being reset. Value of qa mode was being changed but change event wasn't being dispatched which is needed to trigger the actual reset.
=> fix: qa advanced setting

django/requirements.txt
Dismissed dependabot PRs this month but Django has a security alert, so we should at least upgrade it to the latest patch version.
=> chore: upgrade django to 5.1.4

django/otto/templates/base.html
Sometimes the login page tries to redirect to /search/, resulting in a 500 error. It turns out that this happens if you click the login button really fast after loading the welcome page. This caused some middleware requests to happen out of order, creating the state mismatch ({"next": "/search/"} vs {"next": "/"}).
This can only happen because search.html is included in the base html template, which is extended by the welcome page. Thus, the fix is as easy as wrapping the search.html inclusion in an if-statement, so it doesn't appear without authentication (i.e. _after_ login).
=> fix: prevent search from loading before login

django/otto/templates/terms_of_use.html
For an unknown-to-me reason, the variable *has to be* named LANGUAGE_CODE for this check to work.
=> fix: language check in terms of use

README.md, django/chat/llm.py, django/laws/management/commands/load_laws_xml.py, django/laws/models.py, django/laws/views.py, django/otto/management/commands/test_laws_query.py, django/otto/management/commands/test_laws_results.txt
- Use JSONB for storing metadata for laws and add GIN index on metadata
- reduced from **2.6s to 0.07s per iteration**
- Build HNSW index *after* loading all laws.
- increases accuracy and performance (see https://www.pinecone.io/blog/hnsw-not-enough/)
- improves speed of loading laws
- Adjust HNSW parameters
- TODO: grid search / benchmark different parameters for laws search specifically.
- Based on benchmarks here: https://www.pinecone.io/learn/series/faiss/hnsw/
Need to manually run `load_laws_xml --reset` when upgrading. For local testing you could do this with the "--small" flag.
=> perf(laws): jsonb metadata index, hnsw params

django/laws/management/commands/load_laws_xml.py, django/laws/static/laws/law_search.js, django/laws/static/laws/style.css, django/laws/utils.py, django/laws/views.py, django/tests/laws/test_laws_views.py
Added Pytest also.
To test manually, search for something in the laws view then click the 3 dots on one of the returned sources. (in main branch, this causes an error)
=> fix: law sources view needs json.loads (after switch to JSONB)

django/Dockerfile
The hosts file started giving a write-protection error. The IP seemed to work and should still work with the Fortigate rule since the rules are IP-based. The Azure Firewall needed to be changed to reflect this, but that's in the otto-infra repo.
=> fix: update GoC root certificate download method in Dockerfile

django/Dockerfile
Writing the hosts file didn't work. Using just the IP without providing header didn't work. This PR fixes that by including the header in the wget request.
=> fix: goc cert IP

django/otto/utils/auth.py, django/otto/views.py
To replicate existing issue:
* on `main` branch, open Otto. Log in. Open a second tab. Log out in that tab. Return to the first Otto tab. After 1 minute, the HTMX request to user_cost will result in the login page being superimposed over the homepage.
To test this branch:
* repeat the same steps. The first tab should redirect to the login page rather than superimposing it.
=> fix: add hx-redirect to login when required

django/chat/views.py, django/tests/chat/test_chat_options.py, django/tests/chat/test_chat_views.py
A follow up on the previous refactor: Move preset browser up PR https://github.com/justicecanada/otto/commit/a746613885f57d99b77c6c3182589f8474f938cf
=> refactor: remove backend code for reset button

django/chat/llm.py
llama index uses this equation to calculate the context size of each text chunk for tree summarization:
context_size_tokens = self.context_window - num_prompt_tokens - self.num_output
where self.num_output is the number of tokens to leave space for the generated output. By default this value was being set to 256 which is not enough in our case especially when we want to generate a long summary. This was causing a context overflow for big documents that heavily exceeded the 128K token input limit because llama index was creating chunks of around 127.7K, which left no room for the model to generate a response, making the response go over the context_window limit.
I set the num_output value to the max output token value of the model (16K tokens in the case of gpt-4o and mini), which might be …
=> fix: context length issue for tree_summarizer

django/librarian/tasks.py, django/librarian/templates/librarian/components/document_list.html, django/librarian/templates/librarian/components/document_status.html, django/locale/translation/translations.json, django/tests/librarian/test_librarian.py
PDFium is not thread safe which created issues during the stress test.
For now, we will just not use it at all.
=> fix: always use Azure OCR for PDFs (no PDFium)

django/librarian/views.py, django/locale/translation/translations.json
When editing libraries, updating the "Chat Uploads" folder now shows the toast message "Chat updated successfully" instead of "Folder updated successfully".
=> fix: toast message has chat update

django/chat/forms.py, django/librarian/templates/librarian/components/document_list.html, django/librarian/templates/librarian/components/list_item_inner.html, django/librarian/templates/librarian/forms/data_source.html, django/librarian/views.py, django/locale/translation/translations.json
Bug introduced in #302 
- creating/updating any data source except chat uploads would result in 500 error
Another way to solve the issue, which I pursued here:
- don't allow users to modify the chat upload folders from within librarian
A couple related improvements:
- only show chats that have Q&A uploads in librarian
- only list chats that have Q&A uploads in the "Select chat" autocomplete widget (in Q&A settings sidebar)
- plus "This chat" always shown too, regardless of whether it has any Q&A uploads yet.
=> fix: librarian bug

django/librarian/tasks.py, django/librarian/templates/librarian/components/document_list.html, django/librarian/templates/librarian/components/document_status.html, django/librarian/utils/process_engine.py, django/otto/utils/common.py, django/requirements.txt, django/tests/librarian/test_librarian.py
Also reverts the removal of Pdfium as default mode for Q&A loading.
Needs to be tested in sandbox with multiple users to ensure no Pdfium errors.
=> fix: pypdfium lock

django/otto/utils/common.py, django/otto/utils/decorators.py
Previously some middleware/decorator checks would return a redirected view inside a HTMX request. This resulted in a "Otto within Otto" swap inside e.g. a modal that was making a not-permitted HTMX request.
=> fix: htmx redirect checks

django/otto/utils/common.py
To test:
* Delete your local django/tld_cache directory
* Restart django
* Add a URL to Q&A mode (bad or good url)
* Ensure tld_cache directory is created with no errors in the django logs
=> fix: tldextract file path

django/Dockerfile
- Fixed the SSL Cert Verification Error: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain`
- Removed wget command from Dockerfile
- Copy cert from local VM and chmod before updating ca certs
- Configured Python to use system CA bundle instead of certifi
=> fix: remove wget command for GoC root certificate installation and configure Python to use system CA bundle

django/chat/views.py, django/librarian/models.py, django/librarian/views.py, django/locale/translation/translations.json
When uploading a file & checking for existing SavedFile with matching hash, also check if file exists on disk.
* if matching hash SavedFile exists with no file on disk, fix it
* if matching hash SavedFile exists and has a file on disk, use it.
* if no matching hash, create a new SavedFile
=> fix: robustness to existing bad SavedFile

django/chat/static/chat/js/scripts.js, django/chat/templates/chat/components/chat_options_accordion.html, django/chat/templates/chat/components/chat_tour_steps.html, django/chat/templates/chat/modals/presets/card.html
When loading a preset, it appeared to work, but the old chat options were being saved again right after loading - thus making the loaded preset NOT actually function.
=> fix: options sidebar / preset loading bugs

django/chat/responses.py
The old logic to display the "files ready for Q&A" message broke in the presence of _exactly one_ corrupted file in a .zip. This is because the logic relied on comparing the number of error docs to the number of _files_, and a .zip counts as only one file despite resulting in multiple docs. I've made the logic more direct, but can't say with confidence whether there's a good reason _not_ to do it this way.
=> fix: errors and successes counted properly from .zip files

django/laws/utils.py, django/laws/views.py, django/tests/laws/test_laws_utils.py
Fixes some "Go to source document" links in laws search.
French regulations and "C.R.C." regulations were the main culprits. There are some quirks to the URLs on the laws website. I've tested with a handful of differently named acts and regulations in English and French and believe this solves the problem, but I can't be sure without loading all of the laws locally and running a test that actually fetches the URLs.
=> fix: laws links

django/cache_tiktoken.py
Hopefully this will fix the following error (directly caused by line 310 of markdown_splitter.py
`tokenizer = tiktoken.get_encoding("cl100k_base")`
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1016)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/django/manage.py", line 23, in <module>
main()
File "/django/manage.py", line 19, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in …
```
=> fix: add cl100k_base encoding to tiktoken cache

.github/workflows/pytest.yml, django/.env.example, django/chat/llm.py, django/chat/responses.py, django/chat/utils.py, django/locale/translation/translations.json, django/otto/management/commands/reset_app_data.py
Addresses some issues I encountered when deploying Sandbox, but applies to the main branch as well.
* update endpoints in .env.example
* handle models that only work with a single prompt
* fill empty messages in chat history (e.g. with filenames uploaded by user or created by bot)
* make chat/utils.py "copy_options" robust to use from within management commands (for loading preset fixtures)
* update "reset_app_data --all" management command to load the library_mini.yaml
=> chore: update .env.example; robustness fixes

django/chat/templates/chat/modals/presets/presets_form.html
The Jinja condition {% if request.user.default_preset.id|stringformat:"s" == preset_id|stringformat:"s" %} is creating a scenario where we are performing the operation '' == '' which returns True, when it should be returning False since both variables are empty.
This is because request.user.default_preset is set to None due to the reset_app_data presets call, and then calling .id on None makes Django templates return an empty string instead of throwing an AttributeError. In the case of preset_id, it is not defined since we never pass it, and somehow Django's stringformat filter converts this to an empty string value also. We can test this in the django shell with the script:
from django.template import Template, Context
none_var=None
template_string = "{{x.id|stringformat:'s'}}"
template …
=> fix: bug for saving default presets for the first time

django/librarian/views.py
https://dev.azure.com/BusinessAnalyticsCentre/BAC%20Agile/_workitems/edit/3320
Polling view now requires library viewing permission, not editing permission. Viewers will no longer get booted with an "unauthorized access" notification when viewing a document's status during processing.
=> fix: access "data source status" as library viewer

django/chat/forms.py, django/locale/translation/translations.json
An HTML tag in the hover text for "Combined/Separate" was mistyped. Fixed now.
=> fix: close tag on form HTML

django/otto/views.py, django/tests/otto/test_otto_views.py
Previous logic for banner management did not properly direct the preview button unless both message_en and message_fr were present, leading to a bad HTMX request (page redundantly displayed within itself). Moving the preview button logic outside of the message check allows it to work reasonably in all circumstances.
=> fix: preview banner now works when message_en and/or message_fr not present

django/chat/models.py, django/tests/chat/test_message_pre_delete.py
Added pre_delete signal to Message in order to delete the upload message Document from the Chat library.
=> fix: delete qa upload message document
