- .devcontainer/devcontainer.json
- .vscode/launch.json
- django/locale/translation/translations.json
Removed the msblack extension reference as it doesn't seem to exist (already installed through "ms-python.black-formatter")
changed debuger type as current one is being deprecated.
> chore: minor setup, vscode tweaks

- .devcontainer/post-create.py
- .devcontainer/post-create.sh
- README.md
- django/.env.example
- setup/.env.example
> [!CAUTION]
> Do not merge until the sandbox resource group is ready for use.
> chore: devcontainer adjustments for new resource group

- README.md
step 8 of the docker container setup section is outdated. It needs to be updated to use the set_admin_user command
> chore: update the docker container setup section of the README

- django/chat/views.py
- django/otto/admin.py
- django/otto/forms.py
- django/otto/metrics/activity_metrics.py
- django/otto/metrics/feedback_metrics.py
- django/otto/rules.py
- django/otto/settings.py
- django/otto/urls.py
- django/otto/views.py
- setup/k8s/celery.yaml
- setup/k8s/configmap.yaml
- setup/k8s/django.yaml
- setup/k8s/ingress.yaml
- setup/k8s/letsencrypt-cluster-issuer.yaml
- setup/k8s/namespace.yaml
- setup/k8s/redis.yaml
- setup/k8s/secrets.yaml
- setup/k8s/storageclass.yaml
- setup/k8s/vectordb.yaml
- setup/run_k8s.sh
- setup/run_terraform.sh
- setup/setup_env.sh
- setup/terraform/locals.tf
- setup/terraform/main.tf
- setup/terraform/modules/acr/main.tf
- setup/terraform/modules/aks/main.tf
> ops: tagging for batch 2

- setup/k8s/celery.yaml
- setup/k8s/django.yaml
- setup/k8s/vectordb.yaml
Django pod keeps crashing in sandbox. This should fix it.
> ops: increase memory, storage, cpu in k8s pods

- django/chat/tasks.py
Fixes 500 error when trying to download resulting translated file.
> fix: failed translation failure

- django/chat/tasks.py
- setup/k8s/celery.yaml
Translated documents can now be saved in aks.
> fix: document translation in aks

- django/requirements.txt
- django/text_extractor/utils.py
- django/text_extractor/views.py
resolves a security issue in dependabot
> chore(deps): update pypdf and remove pypdf2

- django/tests/otto/test_cleanup.py
Fixes a local test failure introduced in #119
> test: fix cleanup test

- setup/.env.dev
- setup/.env.pilot
- setup/.env.prod
- setup/.env.sandbox
- setup/.env.uat
- setup/setup_env.sh
- setup/terraform/main.tf
- setup/terraform/modules/aks/main.tf
- setup/terraform/modules/aks/variables.tf
- setup/terraform/variables.tf
AU-9: explicitly grants BAC TECH admins access to the analytics workspace.
> ops: Log analytics reader role adjustments

- django/chat/static/chat/js/scripts.js
- django/chat/utils.py
Also fixes a small bug with response stopping.
> fix: auto-stop / start chat scrolling when user scrolls

- django/chat/templates/chat/components/chat_welcome.html
- django/locale/translation/translations.json
- django/otto/templates/cost_dashboard.html
- django/otto/views.py
1. fix: an issue where the chart in the cost dashboard would disappear on filter change and the page would have to be refreshed in order for the chart to reappear.
2. feat: shifted the days to include the current day for "Last 7 days", "Last 30 days" and "Last 90 days" filter.
3. updated privacy notice as requested.
> fix: cost dashboard chart disappearing

- .vscode/launch.json
- README.md
- django/librarian/utils/process_engine.py
- django/tests/librarian/test_document_loading.py
- fixes issue where uploading html documents with Windows-1252 characters fails.
- fixes issue where some docx documents failed.
> fix: file upload encoding issues

- django/chat/forms.py
- django/locale/translation/translations.json
- django/otto/fixtures/cost_types.yaml
- django/tests/otto/test_load_test.py
old GPT models removed and renamed. cost types and tests adjusted.
> chore: gpt models modified and load_test adjusted

- django/chat/static/chat/js/scripts.js
- django/chat/templates/chat/components/message_actions.html
Changed the clipboard icon in AI Assistant chat to copy icon.
> refactor: change clipboard icon in AI Assistant chat to copy icon

- django/chat/static/chat/js/sidebar.js
- django/chat/static/chat/style.css
Increased sized of sidebar to a min width of 400 px.
> fix: update sidebar minimum width to improve layout in French

- django/locale/translation/translations.json
- django/otto/fixtures/apps.yaml
Addresses comments made on-prem.
> fix: update French translations

- django/otto/management/commands/update_exchange_rate.py
Also, the pytest would always pass because the exception was being caught in the command try/catch
> fix: URL for exchange rates was date-specific

- django/requirements.txt
- django/requirements_dev.txt
- django/requirements_dev_celery.txt
- django/tests/chat/test_chat_views.py
This should automatically close the dependabot PRs once merged.
> chore: update requirements as per dependabot

- django/locale/translation/translations.json
- django/otto/fixtures/apps.yaml
Going over translations and fixing some of them. Also made some permanent.
Removed unused translations as well.
> fix: French translations (ctnd)

- django/migrate-collectstatic.sh
> fix: localization

- django/locale/translation/translations.json
- django/otto/templates/components/user_cost.html
- django/otto/templates/components/user_menu.html
- django/otto/views.py
> feat: display monthly budget usage in user menu dropdown

- django/otto/tasks.py
> fix: typo in update_laws

- django/chat/static/chat/style.css
- django/chat/templates/chat/components/chat_input.html
magic wand moved beside settings and colored.
> feat: prompt generator icon modified

- django/chat/templates/chat/components/chat_options_sidebar.html
- django/locale/translation/translations.json
> refactor: Move preset browser up

- django/locale/translation/translations.json
- django/otto/forms.py
- django/otto/views.py
Addressing feedback from VA number 2.12
> fix: validate hidden fields in feedback form

- django/locale/translation/translations.json
- django/otto/forms.py
- django/otto/views.py
Cherry picked from Pilot branch.
> fix: validate hidden fields in feedback form (#291)

- .github/workflows/localization.yml
- .github/workflows/pytest.yml
- django/locale/translation/translations.json
- django/otto/settings.py
- django/otto/static/js/script.js
- django/otto/templates/components/toasts.html
- django/otto/templates/components/user_cost.html
- django/otto/urls.py
- django/otto/utils/middleware.py
- django/otto/views.py
Cherry picked from Pilot branch
> fix: session timeout (ignore user_cost polling) (#293)

- django/chat/responses.py
- django/chat/utils.py
Fixes a bug in main :| which seems to have been introduced by llama_index upgrade...
> fix: check for none messages/responses

- django/.dockerignore
- django/migrate-collectstatic.sh
Needs to be merged with: https://github.com/justicecanada/otto-infrastructure/pull/21
> refactor: moved localization to build step.

- django/librarian/utils/extract_emails.py
Added cc and bcc to email extraction markdown.
> fix: add cc and bcc to email markdown

- django/chat/static/chat/css/highlightjs.css
- django/chat/static/chat/css/style.css
- django/chat/templates/chat/chat.html
- django/chat/templates/chat/chat_readonly.html
- django/laws/templates/laws/laws.html
- django/otto/static/css/variables.css
- django/otto/static/thirdparty/css/highlightjs.css
Added chat-message-text-color variable
Changed dark mode color of chat-message-bg
> fix: code block dark mode

- django/chat/responses.py
- django/locale/translation/translations.json
Add corrupt files array to keep track of the corrupt files
Wrap the function in a try block
Remove corrupt file name from titles in the except block and append it to the corrupt files array
Log the error
Continue to the next file
Create corrupt file string with all the corrupt files and append back to titles to present to user with the error message
> fix: summarize bad file

- django/chat/templates/chat/components/chat_welcome.html
- django/locale/translation/translations.json
Integrate recommendations from legal practitioners to ensure disclaimers are more easily understood.
> chore: update warning text

- .devcontainer/Dockerfile
- .github/dependabot.yml
- build_and_push_image.ps1
- django/Dockerfile
- django/Dockerfile.sandbox
Change docker image from bullseye to bookworm. Fixes critical security vulnerability CVE-2024-38428
> chore: change docker image

- django/.dockerignore
- django/Dockerfile
- Dockerfile takes variables and passes them into the localization function
> fix: update Dockerfile to load environment variables

- django/chat/fixtures/presets.yaml
- django/chat/models.py
- django/chat/static/chat/js/presetModal.js
- django/chat/templates/chat/chat.html
- django/chat/templates/chat/modals/presets/card.html
- django/chat/templates/chat/modals/presets/card_list.html
- django/chat/templates/chat/modals/presets/shared_icon.html
- django/chat/views.py
- django/locale/translation/translations.json
> feat: filter presets

- .gitignore
- django/chat/responses.py
- django/laws/forms.py
current code doesn't add duplicate documents to total count of uploaded docs, which is technically accurate but confusing to user
> fix: 0 documents added

- django/chat/templates/chat/components/chat_message.html
- django/chat/utils.py
- django/chat/views.py
> feat: show llm name in response message

- django/locale/translation/translations.json
- django/text_extractor/templates/text_extractor/completed_documents.html
- django/text_extractor/templates/text_extractor/ocr.html
- django/text_extractor/templates/text_extractor/warn_dont_leave.html
- django/text_extractor/views.py
> feat: warn user not to leave text extractor

- django/transcriber/static/transcriber/style.css
- django/transcriber/templates/transcriber.html
- django/transcriber/utils.py
- django/transcriber/views.py
Restores Jason's old style formats, adds nicer sentence consolidating to cleanup, and includes timestamps in notes (made clickable on client side)
> feat: add some qol improvements to transcriber app

- .devcontainer/devcontainer.json
- .vscode/settings.json
To resolve an issue when using Rancher for devcontainers in VScode.
You may also need to edit this setting manually in VScode:
1. 
2.
> dev: disable wayland in devcontainer

- django/chat/llm.py
- django/locale/translation/translations.json
Various translation bugs (see tickets below) fixed.
https://dev.azure.com/BusinessAnalyticsCentre/BAC%20Agile/_boards/board/t/Otto/Projects?workitem=3247
https://dev.azure.com/BusinessAnalyticsCentre/BAC%20Agile/_boards/board/t/Otto/Projects?workitem=3245
> fix: translation problems

- django/chat/fixtures/presets.yaml
I forgot to update the French versions of the default presets fixture.
> chore: update french prompts in presets.yaml

- django/chat/utils.py
French prompt generated with French input now, previously it would output English prompt even with French input.
> fix: prompt generator language

- django/locale/translation/translations.json
- django/otto/context_processors.py
- django/otto/rules.py
- django/otto/static/style.css
- django/otto/templates/base.html
- django/otto/templates/components/message_from_admins.html
- django/otto/templates/components/user_menu.html
- django/otto/templates/manage_banner.html
- django/otto/urls.py
- django/otto/views.py
> feat: temporary banner message from admins

- django/locale/translation/translations.json
> fix: translations

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- django/laws/utils.py
- django/laws/views.py
- django/tests/laws/test_laws_utils.py
https://dev.azure.com/BusinessAnalyticsCentre/BAC%20Agile/_boards/board/t/Otto/Projects?workitem=3341
> fix: remove bug where nested lists could be rendered as code blocks
